apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontent-deployment
  namespace: chat-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: chatapp-frontent
          image: rajnavneet9931/chatapp-frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: NODE_ENV
              value: "production"
