apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: chat-app

type: Opaque

data:
  jwt-secret: ZXlKMGVYQWlPaUpLVjFRaUxDSmhiR2NpT2lKSVV6STFOaUo5LmV5SnBjM01pT2lKUGJteHBibVVnU2xkVUlFSjFhV3hrWlhJaUxDSnBZWFFpT2pFM016UTNNakE1TXpBc0ltVjRjQ0k2TVRjMk5qSTFOamt6TUN3aVlYVmtJam9pZEhKaGFXNTNhWFJvYzJoMVltaGhiUzVqYjIwaUxDSnpkV0lpT2lKcWNtOWphMlYwUUdWNFlXMXdiR1V1WTI5dElpd2lSMmwyWlc1T1lXMWxJam9pUVdaNllXd2lMQ0pUZFhKdVlXMWxJam9pVW05amEyVjBJaXdpUlcxaGFXd2lPaUpxY205amEyVjBRR1Y0WVcxd2JHVXVZMjl0SWl3aVVtOXNaU0k2V3lKRVpYWlBjSE1pTENKUWNtOXFaV04wSUVGa2JXbHVhWE4wY21GMGIzSWlYWDAuZWhlbEJiVVUySUZKOE01eHpRTF9VRmF0TXhDTVNvakFPcVdRYVpRZ3J3aw==
  cloudinary-cloud-name: ZHRiZTY0cHlt
  cloudinary-api-key: NDM5NDQ0MzU0OTc4NTk3
  cloudinary-api-secret: WTBIOW1kOURYakc1cng5MW5WUnJPTjlYQVE0
